<?php

namespace Database\Factories;

use App\Models\Category;
use App\Models\Company;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Job>
 */
class JobFactory extends Factory {
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array {

        $jobs = [
            'Software Developer',
            'Web Developer',
            'Database Administrator',
            'Network Engineer',
            'Systems Administrator',
            'IT Security Analyst',
            'Systems Analyst',
            'DevOps Engineer',
            'Cloud Solutions Architect',
            'Software Engineer',
            'IT Project Manager',
            'IT Consultant',
            'Business Analyst (IT)',
            'Network Administrator',
            'IT Support Specialist',
            'Quality Assurance (QA) Engineer',
            'Cybersecurity Analyst',
            'Data Scientist',
            'UX/UI Designer (with IT focus)',
            'IT Manager',
            'IT Director',
            'IT Auditor',
            'IT Trainer',
            'Technical Writer (IT)',
            'IT Operations Manager',
            'Mobile App Developer',
            'Frontend Developer',
            'Backend Developer',
            'Full Stack Developer',
            'UI/UX Developer',
            'Software Development Engineer in Test (SDET)',
            'Release Engineer',
            'IT Administrator',
            'IT Coordinator',
            'IT Technician',
            'IT Specialist',
            'IT Analyst',
            'IT Compliance Officer',
            'IT Procurement Specialist',
            'IT Asset Manager',
            'IT Trainer/Instructional Designer',
            'IT Recruiter',
            'IT Sales Representative',
            'IT Business Analyst',
            'IT Service Desk Analyst',
            'IT Infrastructure Manager',
            'IT Operations Analyst',
            'IT Change Manager',
            'IT Incident Responder',
            'IT Risk Analyst',
            'IT Trainer/Instructional Designer',
            'Technical Writer (IT)',
            'User Interface (UI) Designer',
            'User Experience (UX) Designer',
            'Technology Educator',
            'IT Curriculum Developer',
            'IT Instructor',
            'Computer Science Educator',
            'IT Learning Specialist',
            'Technical Support Specialist',
            'IT Systems Educator',
            'Network Security Educator',
            'Cloud Computing Instructor',
            'Programming Language Instructor',
            'IT Workshop Facilitator',
            'Data Analytics Trainer',
            'Machine Learning Educator',
            'IT Researcher',
            'Technology Integration Specialist',
            'Digital Learning Consultant',
            'Virtual Reality (VR) Instructor',
            'Augmented Reality (AR) Educator',
            'IT Education Consultant',
            'IT Training Coordinator',
            'Cybersecurity Trainer',
            'IT Outreach Coordinator',
            'Digital Literacy Instructor',
            'Online Learning Specialist',
            'Computer Science Mentor',
            'Technology Coach',
            'Coding Bootcamp Instructor',
            'IT Project-Based Learning Facilitator',
            'EdTech Specialist',
            'Interactive Media Educator',
            'Tech Workshop Organizer',
            'Programming Club Advisor',
            'Tech Camp Instructor',
            'IT Career Counselor',
            'Mobile App Development Teacher',
            'E-Learning Developer',
            'Computer Hardware Educator',
            'Game Development Instructor',
            'STEM Education Coordinator',
            'Robotics Trainer',
            'IT Leadership Coach',
            'Coding for Kids Instructor',
            'IT Outreach Specialist',
            'AI Developer',
            'Machine Learning Engineer',
            'Deep Learning Scientist',
            'Artificial Intelligence Specialist',
            'Computer Vision Engineer',
            'Natural Language Processing (NLP) Engineer',
            'AI Research Scientist',
            'Algorithm Engineer',
            'Data Scientist',
            'AI Systems Architect',
            'Neural Network Engineer',
            'Robotics Engineer',
            'AI Software Engineer',
            'Cognitive Computing Developer',
            'Automation Engineer',
            'AI Project Manager',
            'Speech Recognition Engineer',
            'AI Ethics Specialist',
            'AI Product Manager',
            'Reinforcement Learning Engineer',
            'AI Data Analyst',
            'Chatbot Developer',
            'Autonomous Systems Engineer',
            'AI Integration Specialist',
            'Predictive Analytics Engineer',
            'AI Consultant',
            'AI Trainer',
            'Human-AI Interaction Designer',
            'AI Model Validator',
            'AI Infrastructure Engineer',
            'Quantum Computing Scientist',
            'AI for Healthcare Developer',
            'AI for Finance Specialist',
            'AI for Marketing Analyst',
            'AI for Cybersecurity Analyst',
            'AI for Gaming Developer',
            'AI for Education Researcher',
            'AI for Renewable Energy Engineer',
            'AI for Agriculture Specialist',
            'AI for Supply Chain Analyst',
            'AI for Human Resources Consultant',
            'AI for Customer Support Engineer',
            'AI for Legal Researcher',
            'AI for Social Media Analyst',
            'AI for Transportation Engineer',
            'AI for Space Exploration Scientist',
        ];


        $experienceLevels = ['Junior', 'Mid', 'Senior'];
        $randomExperienceLevel = fake()->randomElements($experienceLevels, fake()->numberBetween(1, 3));

        $jobDescriptionElements = [
            "We are seeking a dynamic and skilled individual.",
            "Join our innovative global team.",
            "Play a pivotal role in delivering cutting-edge solutions.",
            "Responsibilities span the entire software development lifecycle.",
            "From initial scoping to ongoing application support.",
            "Tech stack includes frameworks like .Net and Angular,",
            "Utilize cloud services such as Azure,",
            "As a key member of our workforce, your primary focus will be delivering cutting-edge SAAS solutions that seamlessly blend complexity with user-friendly and intuitive functionalities.",
            "Embrace emerging technologies like Redis, Puppeteer, and SignalR.",
            "Immerse yourself in an environment that fosters creativity.",
            "Collaborate with cross-functional teams",
            "Tackle challenging problems",
            "Contribute to the development of advanced software solutions.",
            "Your responsibilities will span the entire software development lifecycle, from initial scoping to ongoing application support.",
            "Passionate about technology,",
            "Thrive on solving complex challenges,",
            "Be part of a collaborative and diverse organization.",
            "Embark on an exciting journey with us!",
            "Innovate and contribute to the evolution of our products.",
            "Drive the development of scalable and efficient code.",
            "Work on diverse projects that challenge and inspire.",
            "In our technology stack, we leverage various frameworks and technologies such as .Net, Angular, Azure, Redis, Puppeteer, SignalR, and more.",
            "Collaborate closely with UX/UI designers for intuitive interfaces.",
            "Stay abreast of industry trends and incorporate best practices.",
            "Participate in code reviews to ensure high-quality standards.",
            "Create robust and secure software solutions,",
            "Translate business requirements into technical specifications.",
            "Thrive in an agile and fast-paced development environment.",
            "Demonstrate a passion for continuous learning,",
            "Shape the future of technology with us,",
            "Lead and mentor junior members of the development team,",
            "If you are passionate about technology, enjoy tackling complex challenges, and want to be part of a forward-thinking organization, we encourage you to apply!",
            "Contribute to a positive and inclusive team culture,",
            "Explore new tools and technologies to enhance our stack.",
            "Ensure code is maintainable, scalable, and well-documented.",
            "Adapt and respond to changing project requirements,",
            "We are seeking a dynamic and skilled software engineer to join our innovative global team.",
            "This is a fantastic opportunity to contribute to the development of advanced software solutions and work with a diverse and talented team.",
        ];
        $randomNumber = fake()->numberBetween(6, 10);
        shuffle($jobDescriptionElements);
        $randomElements = array_slice($jobDescriptionElements, 0, $randomNumber);
        $combinedDescription = implode(" ", $randomElements);

        $benefits = [
            "• Health Insurance",
            "• Retirement Plans",
            "• Paid Time Off",
            "• Flexible Work Schedule",
            "• Professional Development",
            "• Employee Assistance Programs",
            "• Tuition Reimbursement",
            "• Wellness Programs",
            "• Family-Friendly Policies",
            "• Career Advancement Opportunities",
            "• Performance Bonuses",
            "• Transportation Benefits",
            "• Employee Discounts",
            "• Social Events",
            "• Casual Dress Code"
        ];
        $randomBenefits = fake()->randomElements($benefits, fake()->numberBetween(3, 8));

        $responsibilities = [
            "• Design and implement software solutions that meet business requirements",
            "• Collaborate with cross-functional teams to define, design, and ship new features",
            "• Write clean, maintainable, and efficient code",
            "• Conduct code reviews to ensure code quality and adherence to coding standards",
            "• Troubleshoot, debug, and resolve software defects and issues",
            "• Participate in agile development methodologies and contribute to team discussions",
            "• Develop and implement cybersecurity policies, standards, and procedures",
            "• Monitor network traffic for security events and conduct security assessments",
            "• Respond to and investigate security incidents, providing analysis and recommendations",
            "• Collaborate with IT teams to implement security measures and best practices",
            "• Conduct security awareness training for employees on cybersecurity best practices",
            "• Stay up-to-date on emerging threats and vulnerabilities in the cybersecurity landscape",
            "• Manage and maintain enterprise-level IT systems and infrastructure",
            "• Install, configure, and troubleshoot servers, networks, and cloud services",
            "• Perform routine system updates, backups, and security patches",
            "• Collaborate with cross-functional teams to design and implement IT solutions",
            "• Provide technical support to end-users and resolve IT-related issues",
            "• Document system configurations, processes, and procedures"
        ];
        $randomResponsibilities = fake()->randomElements($responsibilities, fake()->numberBetween(3, 8));

        $qualifications = [
            "• Bachelor's degree in Computer Science or a related field",
            "• Minimum of 5 years of experience in software development",
            "• Proficient in multiple programming languages, including Java, Python, or C++",
            "• Strong problem-solving and debugging skills",
            "• Experience with front-end and back-end development frameworks",
            "• Familiarity with version control systems (e.g., Git) and continuous integration",
            "• Bachelor's degree in Cybersecurity, Information Technology, or a related field",
            "• Certified Information Systems Security Professional (CISSP) certification",
            "• Minimum of 3 years of experience in IT security",
            "• Knowledge of network security protocols and technologies",
            "• Experience in conducting security assessments and vulnerability testing",
            "• Familiarity with security information and event management (SIEM) systems",
            "• Bachelor's degree in Information Technology or a related field",
            "• Minimum of 2 years of experience in systems administration",
            "• Proficient in Windows and Linux operating systems",
            "• Experience with cloud platforms such as AWS or Azure",
            "• Strong troubleshooting and problem-solving skills",
            "• Familiarity with scripting languages (e.g., PowerShell, Bash)"
        ];
        $randomQualifications = fake()->randomElements($qualifications, fake()->numberBetween(3, 8));

        $categories = [
            'Software Development',
            'Web Development',
            'Database Administration',
            'Network Engineering',
            'Cybersecurity',
            'Project Management',
            'Business Analysis',
            'Operations Management',
            'Executive Leadership',
            'Business Development',
            'Digital Marketing',
            'Content Marketing',
            'Public Relations',
            'Social Media Management',
            'Marketing Analytics'
        ];

        return [
            'title' => fake()->randomElement($jobs),
            'location' => fake()->streetAddress . ', ' . fake()->city,
            'description' => $combinedDescription,
            'qualifications' => implode(PHP_EOL, $randomQualifications),
            'responsibilities' => implode(PHP_EOL, $randomResponsibilities),
            'salary' => fake()->randomNumber(5),
            'benefits' => implode(PHP_EOL, $randomBenefits),
            'experience_level' => implode("-", $randomExperienceLevel),
            'category' => fake()->randomElement($categories),
            'application_deadline_at' => $this->faker->dateTimeBetween('+1 month', '+2 months'),
            'created_at' => fake()->dateTimeBetween('-1 month', 'now'),
            'company_id' => function () {
                return Company::inRandomOrder()->first()->id;
            },
        ];
    }
}
